extends Node

static var game_logic = GameLogic.new()

func say_hello():
	print("hello")
const PACKAGE_NAME = 'com.clareentertainment.tressette'
const GAME_MODE = {
	TRESSETTE = 0,
	BRISCOLA = 1,
}

const PLAYER_MODE = {
	SOLO = 2,
	TEAM = 4
}

const CARDS = {
	CARDBACK = 52
}

const CMDs = {
	PING_PONG = 0,
	LOGIN = 1,
	CREATE_GUEST_ACCOUNT = 2,
	LOGIN_FIREBASE = 3,
	APP_VERSION = 5,
	TEST_MESSAGE = 100,
	GENERAL_INFO = 1000,
	USER_INFO = 1001,
	LOG_OUT = 1002,
	UPDATE_MONEY = 1003,
	QUICK_PLAY = 2000,
	GAME_INFO = 2001,
	REGISTER_LEAVE_GAME = 2002,
	NEW_USER_JOIN_MATCH = 2003,
	USER_LEAVE_MATCH = 2004,
	DEAL_CARD = 2005,
	PLAY_CARD = 2006,
	START_GAME = 2007,
	NEW_HAND = 2008,
	END_HAND = 2009,
	DRAW_CARD = 2010,
	END_GAME = 2011,
	PREPARE_START_GAME = 2012,
	TABLE_LIST = 2013,
	NEW_ROUND = 2014,
	CREATE_TABLE = 2015,
	JOIN_TABLE_BY_ID = 2016,
	
	NEW_INGAME_CHAT_MESSAGE = 3000,
	CHAT_EMOTICON = 3001,
	
	PAYMENT_GOOGLE_CONSUME = 4000,
	PAYMENT_SUCCESS = 4001,
	PAYMENT_APPLE_CONSUME = 4002,
	PAYMENT_APPLE_FINISHED_TRANSACTION = 4003,
	SHOP_CONFIG = 4100,
	
	SEARCH_FRIEND = 5000,
	ADD_FRIEND = 5001,
	ACCEPT_FRIEND_REQUEST = 5002,
	REMOVE_FRIEND = 5003,
	REJECT_FRIEND_REQUEST = 5004,
	FRIEND_LIST = 5005,
	FRIEND_REQUESTS = 5006,
	NEW_FRIEND_REQUEST = 5007,
	NEW_FRIEND_ACCEPTED = 5008,
	RECOMMEND_FRIENDS = 5009,
	
	CHANGE_AVATAR = 6000,
	CHEAT_GOLD_USER = 6001,
	CLAM_SUPPORT = 6002,
}

const PROTOBUF = {
	PACKETS = preload("res://scripts/protobuf/packets.gd")
}

const CARD_STYLES = {
	CLASSIC = 0,
	MODERN = 1,
}

const GUI_ZORDER = {
	PICK_AVATAR = 10
}

const LOGIN_TYPE = {
	NONE = -1,
	GUEST = 0,
	FIREBASE = 1
}

const CARD_FACE_STATE = {
	UP = 0,
	DOWN = 1
}
const LIRA_TEXT = "₤"

const DELETE_ACCOUNT_URL = 'https://clareentertainment.my.canva.site/tressette-delete-account'
const PRIVACY_POLICY_URL = 'https://clareentertainment.my.canva.site/tressette-policy'
const TERMS_OF_SERVICE_URL = 'https://clareentertainment.my.canva.site/term-of-services'
